### PR TITLE
✨ Attach the original `Error` as a cause of thrown one

### PR DESCRIPTION
**Pull request by dubzzz**
**_Category:_**

- [x] ✨ Introduce new features
- [ ] 📝 Add or update documentation
- [ ] ✅ Add or update tests
- [ ] 🐛 Fix a bug
- [ ] 🏷️ Add or update types
- [ ] ⚡️ Improve performance
- [ ] _Other(s):_ ...
  
  

**_Potential impacts:_**

- [ ] Generated values
- [ ] Shrink values
- [ ] Performance
- [ ] Typings
- [ ] _Other(s):_ ...

### CODE REVIEW

**Comment by dubzzz** [comment]
Quick tour of the existing test frameworks and how they behave against something like:

image

**Jest**

image

**Vitest**

image

**Node (16.14.0)**

image

**Comment by dubzzz** [comment]
Waiting the end of my work on 'better handling of poisoning' before reliving this PR. In order not to break the existing users, the error with cause will be provided as an opt-in option. Helpers around test runners (not any for vitest yet but will come) will probably enforce it according to how well the test runner handle them.

**Comment by jasikpark** [comment]
This will be nice so I can stop using:

`fc.context(), (input, ctx) => {  ctx.log(`input: ${input}, output: ${functionUnderTest(input)}`); }`

in my property tests

**Comment by dubzzz** [comment]
Interested to now why you need this pattern? By the way, you can override the default error reporter if needed

**Comment by jasikpark** [comment]
I have a pretty similar goal to https://github.com/dubzzz/fast-check/issues/660 i think - I want to see the expected vs actual values on `jest` expect errors in vitest

**Comment by dubzzz** [comment]
**ava 4.3.3**

image

**jasmine 4.4.0**

image

**jest 28.1.2**

image

**mocha 10.0.0**

image

**node 16.14.0**

image

**vitest 0.17.0**

image

**Comment by dubzzz** [comment]
please deploy

**Comment by dubzzz** [comment]
With the new flag against vitest:

image

image


<details>
<summary>
Code snippet
</summary>

```js
import { test, expect } from "vitest";
import fc from "fast-check";

fc.configureGlobal({ errorWithCause: true });

test("error cause", () => {
  fc.assert(
    fc.property(fc.integer(), (n) => {
      return n <= 10;
    })
  );
});

test("error cause (expect)", () => {
  fc.assert(
    fc.property(fc.integer(), (n) => {
      expect(n).toBeLessThanOrEqual(10);
    })
  );
});
```
</details>

With the flag against node:

image
image


<summary>
Code snippet 1
</summary>

```js
const fc = require("fast-check");

fc.configureGlobal({ errorWithCause: true });

fc.assert(
  fc.property(fc.integer(), (n) => {
    return n <= 10;
  })
);
```
</details>

<summary>
Code snippet 2
</summary>

```js
const assert = require("assert");
const fc = require("fast-check");

fc.configureGlobal({ errorWithCause: true });

fc.assert(
  fc.property(fc.integer(), (n) => {
    assert(n <= 10);
  })
);
```
</details>

**Pull request merged**
