### PR TITLE
Missing fc.frequency documentation

### PR DESCRIPTION
**Pull request by giovannyg**
## Why is this PR for?
Adding fc.frequency doc
Describe the reason of this PR or give a link towards the associated issue.
https://github.com/dubzzz/fast-check/issues/441
## In a nutshell

✔️ Documentation improvement

## Potential impacts

If you expect some noticeable impacts with your change please explain.

Here are some examples of impacts that might be reported into this section:
- Generated values impact,
- Shrink values impact,
- Performance impact,
- Typings impact

### CODE REVIEW

**Comment by dubzzz** [comment]
Suggestion:

> randomly chooses an arbitrary at each new generation. Should be provided with at least one arbitrary. Probability to select a specific arbitrary is based on its weight, the higher it is the more it will be probable. It preserves the shrinking capabilities of the underlying arbitrary

**Comment by giovannyg** [comment]
Thank you, I'm going to create a new pr.

**Comment by dubzzz** [comment]
Thanks for the contribution 😁

**Comment by giovannyg** [comment]
Thanks for letting me add some lines to your project, It's been a good starting point as my first pr to open source.

**Pull request merged**
